### ISSUE TITLE
start_time Option does nothing

### ISSUE THREAD

**Issue by DRKSLV** [damianociarla/node-ffmpeg#66]
In my testing, i couldnt get fnExtractFrameToJPG(path_out, {number:1, start_time: \<time in secs\>}) to save a Frame of a given time.

I have no idea why.

**Comment by LMulvey** [comment]
This issue is fixed in the repository as of seven years ago (e1a2787d2ba0538956c8f696bcb5ea6286ae09e2) but not published. You have three options:
1) Point your package.json directly to this repository: https://github.com/damianociarla/node-ffmpeg
2) Use a forked/fixed version I published: https://www.npmjs.com/package/ffmpeg-fork
3) Fork and publish your own version.

**Comment by DRKSLV** [comment]
Thanks ( i read this long ago but didnt respond or close the issue 😓)
